### ISSUE TITLE
console.log al validar RUT

### ISSUE THREAD

**Issue by matiasespinozah** [Edddddddd/angular-13-rut-chileno#1]
Hola amigo, primero que todo genial tu librería me ahorraste mucho tiempo!! y las que existían anteriormente ya casi ni funcionaban :c

te comento que probando tu lib encontré un detalle y es que cuando se valida el RUT estas mostrando unos console.log que son bien molestos te adjunto la parte del código donde los encontré

en el método del rutService -> validaRutForm
``` javascript
// Validar que el Cuerpo coincide con su Dígito Verificador
console.log(dvEsperado);
console.log(dv);
console.log(dvEsperado.toString() !== dv)
if (dvEsperado.toString() !== dv && cuerpo.length >= 0) {
    return {
        rutnovalido: true
    };
} else {
    return null;
  }
}
```

saludos!! y gran trabajo 😄

**Comment by Edddddddd** [comment]
Hola Matias
Muchas gracias por tu observación 
Ya actualice la version a la 1.0.4 con los cambios que solicitaste.
Espero que te sea de ayuda, cualquier consulta estoy para ayudarte referente al repo.
Saludos
